[package]
name = "easy_microbit"
version = "0.1.0"
authors = ["cgm616 <cgm616@me.com>"]

[dependencies]
panic-semihosting = "0.5.1"
nrf51 = "0.5.0"
cortex-m-rt = "0.6.6"
alloc-cortex-m = "0.3.5"
nb = "0.1.1"

[dependencies.cortex-m]
features = ["inline-asm"]
version = "0.5.2"

[dependencies.nrf51-hal]
features = ["rt"]
version = "0.5.5"

[patch.crates-io]
nrf51 = { git = "https://github.com/therealprof/nrf51.git", features = ["rt"] }

[profile.dev]
debug = true

[profile.release]
debug = true
lto = true
opt-level = "s"

